# Generated by Django 4.2.5 on 2023-09-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0002_cart_developers_orderitems_orders_publishers_reviews_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
    ]
