# Generated by Django 4.2.5 on 2023-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0003_remove_games_developer_id_remove_games_publisher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='big_pic',
            field=models.URLField(default='Gemukyu_App/static/images/GimukyuHomeIcon.png'),
        ),
        migrations.AddField(
            model_name='games',
            name='small_pic',
            field=models.URLField(default='Gemukyu_App/static/images/GimukyuHomeIcon.png'),
        ),
    ]
