# Generated by Django 4.2.5 on 2023-11-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0004_remove_users_password_hash_users_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
