# Generated by Django 4.2.5 on 2023-11-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0004_games_big_pic_games_small_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='big_pic',
            field=models.CharField(default='/static/images/GimukyuHomeIcon.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='games',
            name='small_pic',
            field=models.CharField(default='/static/images/GimukyuHomeIcon.png', max_length=200),
        ),
    ]
