# Generated by Django 4.2.5 on 2023-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0005_alter_games_big_pic_alter_games_small_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_codes',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
