# Generated by Django 4.2.5 on 2023-11-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0005_alter_games_big_pic_alter_games_small_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('small_link', models.CharField(max_length=255)),
                ('medium_link', models.CharField(max_length=255)),
                ('large_link', models.CharField(max_length=255)),
                ('banner_link', models.CharField(max_length=255)),
                ('game_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='image_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
