# Generated by Django 4.2.5 on 2023-11-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0006_discount_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='big_pic',
            field=models.CharField(default='GemukyuHomeIcon.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='games',
            name='small_pic',
            field=models.CharField(default='GemukyuHomeIcon.png', max_length=200),
        ),
    ]
