# Generated by Django 4.2.5 on 2023-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0007_alter_games_big_pic_alter_games_small_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
