# Generated by Django 4.2.5 on 2023-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gemukyu_App', '0008_cart_applied_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='applied_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
